# Generated by Django 2.2 on 2019-12-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=50)),
                ('alturaTacon', models.FloatField(blank=True, default=None, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('forro', models.CharField(max_length=50)),
                ('tacon', models.CharField(max_length=50)),
                ('capellada', models.CharField(max_length=50)),
                ('alturaSuela', models.FloatField(blank=True, default=None, null=True)),
                ('color', models.CharField(max_length=50)),
                ('peso', models.FloatField(blank=True, default=None, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('plantilla', models.CharField(max_length=50)),
                ('suela', models.CharField(max_length=50)),
                ('ocasion', models.CharField(max_length=50)),
                ('talla', models.IntegerField(blank=True, default=None, null=True)),
                ('precio', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
